Django/DjangoT1.11_LTS/40_Update Data/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^sosmed/', include('sosmed.urls',namespace='sosmed')),
    url(r'^admin/', admin.site.urls),
]

Django/DjangoT1.11_LTS/40_Update Data/sosmed/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
	url(r'^update/(?P<update_id>[0-9]+)$', views.update, name='update'),
	url(r'^create/$',views.create, name='create'),
	url(r'^$',views.list, name='list'),
]

Django/DjangoT1.11_LTS/40_Update Data/sosmed/models.py
from django.db import models

# Create your models here.

class Instagram(models.Model):
	nama_depan	  	= models.CharField(max_length=100)
	nama_belakang 	= models.CharField(max_length=100)
	username		= models.CharField(max_length=100)

	def __str__(self):
		return "{}.{}".format(self.id,self.username)

Django/DjangoT1.11_LTS/40_Update Data/sosmed/forms.py
from django import forms

from .models import Instagram

class InstagramForm(forms.ModelForm):
	class Meta:
		model = Instagram
		fields =[
			'nama_depan',
			'nama_belakang',
			'username',
		]

Django/DjangoT1.11_LTS/40_Update Data/sosmed/views.py
from django.shortcuts import render, redirect

# Create your views here.

from .models import Instagram
from .forms import InstagramForm

def update(request,update_id):
	akun_update = Instagram.objects.get(id=update_id)
	
	data = {
		'nama_depan'	: akun_update.nama_depan,
		'nama_belakang'	: akun_update.nama_belakang,
		'username'		: akun_update.username,
	}
	akun_form = InstagramForm(request.POST or None, initial=data, instance=akun_update)

	if request.method == 'POST':
		if akun_form.is_valid():
			akun_form.save()

		return redirect('sosmed:list')

	context = {
		"page_title":"Update akun",
		"akun_form":akun_form,
	}

	return render(request,'sosmed/create.html',context)


def delete(request,delete_id):
	Instagram.objects.filter(id=delete_id).delete()
	return redirect('sosmed:list')

def create(request):
	akun_form = InstagramForm(request.POST or None)

	if request.method == 'POST':
		if akun_form.is_valid():
			akun_form.save()

		return redirect('sosmed:list')

	context = {
		"page_title":"Tambah akun",
		"akun_form":akun_form,
	}

	return render(request,'sosmed/create.html',context)

def list(request):
	semua_akun = Instagram.objects.all()

	context = {
		'page_title':'Sosial Media',
		'semua_akun':semua_akun,
	}

	return render(request,'sosmed/list.html',context)

Django/DjangoT1.11_LTS/40_Update Data/sosmed/templates/sosmed/create.html
{% extends "base.html" %}

{% block title %}
	{{page_title}}
{% endblock title %}

{% block contents %}
	<h1>{{page_title}}</h1>
	<form method="POST">
		{% csrf_token %}
		<table>
			{{akun_form.as_table}}
		</table>
		<button type="Submit">Kirim</button>
	</form>
{% endblock contents %}

Django/DjangoT1.11_LTS/40_Update Data/sosmed/templates/sosmed/list.html
{% extends "base.html" %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}
	<h1>{{page_title}}</h1>
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">First</th>
	      <th scope="col">Last</th>
	      <th scope="col">User Name</th>
	      <th scope="col">Hapus</th>
	      <th scope="col">Ubah</th>
	    </tr>
	  </thead>
	  <tbody>   
	    {% for akun in semua_akun %}
	    	<tr>
		      <th scope="row">{{forloop.counter}}</th>
		      <td>{{akun.nama_depan}}</td>
		      <td>{{akun.nama_belakang}}</td>
		      <td>{{akun.username}}</td>
		      <td><a class="btn btn-danger" href="{% url 'sosmed:delete' akun.id %}" title="">Delete</a>
		      <td><a class="btn btn-warning" href="{% url 'sosmed:update' akun.id %}" title="">Update</a>
		    </tr>
	    {% endfor %}
	  </tbody>
	</table>
	<a class="btn btn-primary" href="{% url 'sosmed:create' %}">Tambah</a>
{% endblock contents %}